# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{redclothcoderay}
  s.version = "0.3.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["August Lilleaas", "Matias Korhonen"]
  s.date = %q{2009-10-10}
  s.description = %q{Adds CodeRay syntax highlighting support to RedCloth, with a ‘source’ tag.}
  s.email = ["augustlilleaas@gmail.com", "korhonen.matt@gmail.com"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "lib/redclothcoderay.rb",
     "redclothcoderay.gemspec",
     "test/coderay_options_test.rb",
     "test/redclothcoderay_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://redclothcoderay.rubyforge.org}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{redclothcoderay}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Integrates CodeRay with RedCloth by adding a <source> tag.}
  s.test_files = [
    "test/redclothcoderay_test.rb",
     "test/test_helper.rb",
     "test/redclothcoderay_code_tag.rb",
     "test/coderay_options_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<RedCloth>, [">= 0"])
      s.add_runtime_dependency(%q<coderay>, [">= 0"])
    else
      s.add_dependency(%q<RedCloth>, [">= 0"])
      s.add_dependency(%q<coderay>, [">= 0"])
    end
  else
    s.add_dependency(%q<RedCloth>, [">= 0"])
    s.add_dependency(%q<coderay>, [">= 0"])
  end
end
